config/routes.rb
Rails.application.routes.draw do
  
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  resource :users, only: [:new, :create]

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	validates :body, presence: true
	scope :custom_display, -> {order(:created_at).last(10)}
end

app/models/user.rb
class User < ApplicationRecord
	has_many :messages
	has_secure_password
	validates :username, presence: true, uniqueness: true, length: {minimum: 3, maximum: 15} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
   before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password_digest])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to root_path
    else
      flash.now[:error] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.haml
%h2.ui.center.aligned.icon.header
  %i.circular.blue.comments.inverted.icon
  Say Something

.ui.two.column.grid
  .twelve.wide.column
    .ui.fluid.raised.chatbox.card
      #messages.content
        #message-container.ui.feed
          = render @messages
      .extra.content
        = form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f|
          .field
            .ui.fluid.icon.input
              = f.text_field :body, autocomplete: "off"
              = f.button '<i class="bordered inverted orange arrow up icon"></i>'.html_safe

  .four.wide.column
    .ui.fluid.raised.chatbox.card
      .content
        .ui.inverted.vertical.menu
          %a.active.item
            Home
          %a.item
            Messages
          %a.item
            Friends

app/views/layouts/_header.html.haml
.ui.small.inverted.menu
  .ui.container
    %a.item{:href => root_path}
      Chatroom
    %a.item
      Messages
    .right.menu
      .ui.dropdown.item
        Account
        %i.dropdown.icon
        .menu
          - if logged_in?
            = link_to "Logout", logout_path, method: :delete, class: "item"
          - else
            = link_to "Log in", login_path, class: "item"
      - if !logged_in?
        .item
          = link_to "Log in", login_path, class: "ui primary button"

app/views/layouts/_messages.html.haml
- flash.each do |message_type, message_content|
  %div{:class => "ui #{message_type} message transition"}
    %i.close.icon
    .header
      = message_content

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatApp
    = favicon_link_tag
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    = render :partial=>"layouts/header"
    .ui.container
      = render :partial=>"layouts/messages"
      = yield

app/views/messages/_message.html.haml
.event
  .content
    .summary
      %em>= message.user.username
      \: #{message.body}